{
 "title": "dodge-http",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Dodge-http server uptime",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dodge_uptime" }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "description": "Current open connections on dodge-http server",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dodge_connections_count" }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "description": "Total number of connections made to dodge-http server since bootstrap",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dodge_connections_total" }
   ]
  },
  {
   "title": "Average Http Response Time",
   "type": "gauge",
   "description": "Average Http Response Time (millis)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dodge_http_response_timing)"
    }
   ]
  },
  {
   "title": "Http Request Count by URI",
   "type": "piechart",
   "description": "Http Request Count by URI",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dodge_http_request_count", "legendFormat": "{{uri}} ({{method}})" }
   ]
  },
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "description": "Http Requests Rate / minute",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "dodge_http_request_rate", "legendFormat": "Hits" }
   ]
  },
  {
   "title": "Http Response Time by URI",
   "type": "timeseries",
   "description": "Average Http Response Time (millis) by URI",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg by(uri) (dodge_http_response_timing)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Max Http Response Time by URI",
   "type": "bargauge",
   "description": "Max Http Response Time (millis) by URI",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(uri) (dodge_http_response_timing)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Inbound/Outbound Traffic",
   "type": "timeseries",
   "description": "Inbound/Outbound bytes traffic",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "dodge_inbound_bytes_total", "legendFormat": "Inbound Bytes" },
    { "expr": "dodge_outbound_bytes_total", "legendFormat": "Outbound Bytes" }
   ]
  },
  {
   "title": "In/Out Traffic Byte Rate",
   "type": "timeseries",
   "description": "Inbound/Outbound Tcp traffic byte rate / second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(dodge_inbound_bytes_total[1m]))",
     "legendFormat": "Inbound Bytes"
    },
    {
     "expr": "sum(rate(dodge_outbound_bytes_total[1m]))",
     "legendFormat": "Outbound Bytes"
    }
   ]
  }
 ]
}